name: clean caches

on:
  workflow_dispatch:
    inputs:
      cache_key:
        description: 'cache keys'
        required: false
        default: 'ccache,toolchain'

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: clean caches
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          CACHE_KEYS: ${{ inputs.cache_key }}
        run: |
          success=0
          failed=0
          IFS=',' read -ra KEYS <<< "$CACHE_KEYS"
          for key in "${KEYS[@]}"; do
            gh cache list | awk -v pfx="$key" '$2 ~ pfx { print $2 }' | while read -r cache_id; do
              if gh cache delete "$cache_id"; then
                success=$((success + 1))
              else
                failed=$((failed + 1))
              fi
            done
          done
          echo "success: $success"
          echo "failed: $failed"
